// Review Actions
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const FETCH_SINGLE_REVIEW = 'FETCH_SINGLE_REVIEW'
export const POST_REVIEW = 'POST_REVIEW'
export const EDIT_REVIEW = 'EDIT_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
